Repository eclipse-platform/eclipse.platform.swt, pull requests merged in 2024-12, with the labels that each got.

#1637 Use Edge/WebView2 as the default browser on Windows #1466
  binaries/org.eclipse.swt.cocoa.macosx.aarch64/.settings/.api_filters
  binaries/org.eclipse.swt.cocoa.macosx.x86_64/.settings/.api_filters
  binaries/org.eclipse.swt.gtk.linux.aarch64/.settings/.api_filters
  binaries/org.eclipse.swt.gtk.linux.loongarch64/.settings/.api_filters
  binaries/org.eclipse.swt.gtk.linux.ppc64le/.settings/.api_filters
  binaries/org.eclipse.swt.gtk.linux.riscv64/.settings/.api_filters
  binaries/org.eclipse.swt.gtk.linux.x86_64/.settings/.api_filters
  binaries/org.eclipse.swt.win32.win32.aarch64/.settings/.api_filters
  binaries/org.eclipse.swt.win32.win32.x86_64/.settings/.api_filters
  bundles/org.eclipse.swt/Eclipse SWT Browser/common/org/eclipse/swt/browser/Browser.java
  bundles/org.eclipse.swt/Eclipse SWT Browser/win32/org/eclipse/swt/browser/BrowserFactory.java
  bundles/org.eclipse.swt/Eclipse SWT/common/org/eclipse/swt/SWT.java
  bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Control.java
  examples/org.eclipse.swt.examples/src/org/eclipse/swt/examples/controlexample/BrowserTab.java
  tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/Test_org_eclipse_swt_browser_Browser.java
Labels: noteworthy

#1650 Jenkinsfile: ignoreQualityGate:true #1648
  Jenkinsfile
Labels: bug

#672 Execute browser tests for Edge #671
  bundles/org.eclipse.swt/Eclipse SWT Browser/win32/org/eclipse/swt/browser/Edge.java
  tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/Test_org_eclipse_swt_browser_Browser.java
Labels: edge
