Repository eclipse-platform/eclipse.platform.swt, pull requests merged in 2025-02, with the labels that each got.

#1833 Run the Github verification with GTK4 enabled if it has GTK4 label
  .github/workflows/maven.yml
Labels: gtk4

#1846 Edge: Let WebView2 handle opening new windows by default
  bundles/org.eclipse.swt/Eclipse SWT Browser/win32/org/eclipse/swt/browser/Edge.java
Labels: edge

#1844 Fix Sash Layout Shaking in win32 #62
  bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Control.java
Labels: pmc_approved

#1847 Fix Caret Rescaling for win32 #62
  bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Caret.java
Labels: pmc_approved
